# Generated by Django 5.2.11 on 2026-03-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='imported_from_csv',
        ),
        migrations.DeleteModel(
            name='CSVImportLog',
        ),
    ]
