# Generated by Django 5.2.11 on 2026-03-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_group_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecompletion',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_partnerships', to='api.student'),
        ),
    ]
