# Generated by Django 5.2.11 on 2026-03-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_department_student_department_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
