# Generated by Django 5.2.11 on 2026-03-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_department_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='check_out_time',
        ),
    ]
