# Generated by Django 5.2.11 on 2026-03-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_attendancerecord_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
