# Generated by Django 5.2.12 on 2026-03-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attendancerecord_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(default='82e63ab5-544f-4a0e-85f3-32efd68a8196', on_delete=django.db.models.deletion.PROTECT, to='api.group'),
            preserve_default=False,
        ),
    ]
