# Generated by Django 5.2.12 on 2026-04-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_department_userprofile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalresult',
            name='attendance_count',
        ),
        migrations.RemoveField(
            model_name='finalresult',
            name='exercises_completed',
        ),
        migrations.RemoveField(
            model_name='finalresult',
            name='papers_completed',
        ),
    ]
