# Generated by Django 5.2.12 on 2026-05-24 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_finalresult_attendance_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('praktikum_day', models.IntegerField(help_text='Day number of the praktikum (1, 2, 3, ...)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_days', to='api.group')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('group', 'date')},
            },
        ),
    ]
