# Generated by Django 5.2.12 on 2026-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_labday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['lab_day']},
        ),
        migrations.AlterModelOptions(
            name='papersubmission',
            options={},
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='order',
            new_name='lab_day',
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='necessary_corrections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='paper',
            name='experiment',
        ),
    ]
