# Generated by Django 5.2.12 on 2026-06-17 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_experiment_options_remove_experiment_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.experiment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_completions', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'experiment')},
            },
        ),
    ]
