# Generated by Django 5.2.12 on 2026-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_experimentcompletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['lab_day']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='order',
        ),
        migrations.RemoveField(
            model_name='exercisecompletion',
            name='partner',
        ),
        migrations.AddField(
            model_name='exercise',
            name='lab_day',
            field=models.IntegerField(default=1),
        ),
    ]
