# Generated by Django 5.2.12 on 2026-06-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_exercise_options_remove_exercise_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lab_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_partner_of', to='api.student'),
        ),
    ]
