# Generated by Django 5.2.12 on 2026-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_group_teaching_assistant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='day_type',
            field=models.CharField(choices=[('LAB', 'Lab'), ('LECTURE', 'Lecture')], default='LAB', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'praktikum_day', 'day_type')},
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('day_type__in', ['LAB', 'LECTURE'])), name='attendance_day_type_valid'),
        ),
    ]
