# Generated by Django 5.2.12 on 2026-07-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date', 'day_type')},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='praktikum_day',
            field=models.IntegerField(blank=True, help_text='Curriculum day number for lab sessions (1, 2, 3, ...)', null=True),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('day_type', 'LECTURE'), ('praktikum_day__isnull', True)), models.Q(('day_type', 'LAB'), ('praktikum_day__isnull', False)), _connector='OR'), name='attendance_praktikum_day_matches_day_type'),
        ),
    ]
