# Generated by Django 5.2.12 on 2026-07-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalresult',
            old_name='failure_reason',
            new_name='comment',
        ),
    ]
