# Generated by Django 5.2.12 on 2026-07-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_failure_reason_finalresult_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labday',
            unique_together={('group', 'praktikum_day')},
        ),
        migrations.AlterField(
            model_name='labday',
            name='date',
            field=models.DateField(help_text='Calendar date when this lab day was held'),
        ),
    ]
