# Generated by Django 5.2.12 on 2026-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_labday_unique_together_alter_labday_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('day_type', 'LAB')), fields=('student', 'praktikum_day'), name='unique_lab_attendance_per_student_day'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('day_type', 'LECTURE')), fields=('student', 'date'), name='unique_lecture_attendance_per_student_date'),
        ),
    ]
