# Generated by Django 5.2.12 on 2026-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_experiment_requires_paper_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersubmission',
            name='main_author',
            field=models.BooleanField(default=False),
        ),
    ]
