from django.urls import path
from . import auth_views, views

urlpatterns = [
    path("auth/csrf/", auth_views.CsrfView.as_view(), name="auth-csrf"),
    path("auth/login/", auth_views.LoginView.as_view(), name="auth-login"),
    path("auth/me/", auth_views.MeView.as_view(), name="auth-me"),
    path("auth/logout/", auth_views.LogoutView.as_view(), name="auth-logout"),
    path("students/", views.StudentList.as_view(), name="student-list"),
    path("students/<uuid:pk>/", views.StudentDetail.as_view(), name="student-detail"),
    path(
        "attendance-records/calendar/",
        views.AttendanceCalendarView.as_view(),
        name="attendance-calendar",
    ),
    path(
        "attendance-records/",
        views.AttendanceRecordList.as_view(),
        name="attendance-record-list",
    ),
    path(
        "attendance-records/bulk/",
        views.AttendanceRecordBulkCreateView.as_view(),
        name="attendance-record-bulk",
    ),
    path(
        "attendance-records/delete/",
        views.AttendanceRecordBulkDeleteView.as_view(),
        name="attendance-record-bulk-delete",
    ),
    path(
        "attendance-records/session/",
        views.AttendancePatchSessionView.as_view(),
        name="attendance-record-patch-session",
    ),
    path(
        "students/<uuid:student_pk>/attendance-records/lab/<int:praktikum_day>/",
        views.AttendanceRecordDetail.as_view(),
        name="student-lab-attendance-record-detail",
    ),
    path(
        "students/<uuid:student_pk>/attendance-records/<str:session_date>/",
        views.AttendanceRecordDetail.as_view(),
        name="student-lecture-attendance-record-detail",
    ),
    path(
        "paper-submissions/",
        views.PaperSubmissionList.as_view(),
        name="paper-submission-list",
    ),
    path(
        "paper-submissions/bulk/",
        views.PaperSubmissionBulkCreateView.as_view(),
        name="paper-submission-bulk",
    ),
    path(
        "paper-submissions/<uuid:student_pk>/<uuid:paper_id>/",
        views.PaperSubmissionDetail.as_view(),
        name="paper-submission-detail",
    ),
    path(
        "groups/",
        views.GroupList.as_view(),
        name="group-list",
    ),
    path(
        "groups/<uuid:pk>/",
        views.GroupDetail.as_view(),
        name="group-detail",
    ),
    path(
        "exercises/",
        views.ExerciseList.as_view(),
        name="exercise-list",
    ),
    path(
        "exercises/<uuid:pk>/",
        views.ExerciseDetail.as_view(),
        name="exercise-detail",
    ),
    path(
        "users/",
        views.UserList.as_view(),
        name="user-list",
    ),
    path(
        "experiments/",
        views.ExperimentList.as_view(),
        name="experiment-list",
    ),
    path(
        "experiments/<uuid:pk>/",
        views.ExperimentDetail.as_view(),
        name="experiment-detail",
    ),
    path(
        "experiments/completions/bulk/",
        views.ExperimentCompletionBulkCreateOrUpdateView.as_view(),
        name="experiment-completion-bulk",
    ),
    path(
        "experiments/completions/",
        views.ExperimentCompletionPerStudent.as_view(),
        name="experiment-completion-per-student",
    ),
    path(
        "exercise-completions/",
        views.ExerciseCompletionList.as_view(),
        name="exercise-completion-list",
    ),
    path(
        "exercise-completions/status/",
        views.ExerciseCompletionStatus.as_view(),
        name="exercise-completion-status",
    ),
    path(
        "exercise-completions/upsert/",
        views.ExerciseCompletionUpsertView.as_view(),
        name="exercise-completion-upsert",
    ),
    path(
        "exercise-completions/<uuid:student_pk>/<uuid:exercise_id>/",
        views.ExerciseCompletionDetail.as_view(),
        name="exercise-completion-detail",
    ),
    path(
        "lab-partnerships/",
        views.LabPartnershipPerStudentView.as_view(),
        name="lab-partnership-list",
    ),
    path(
        "lab-partnerships/bulk/",
        views.LabPartnershipBulkView.as_view(),
        name="lab-partnership-bulk",
    ),
    path(
        "students/<uuid:pk>/lab-partner/",
        views.StudentLabPartnerDetailView.as_view(),
        name="student-lab-partner-detail",
    ),
    path("final-results/", views.FinalResultList.as_view(), name="final-result-list"),
    path(
        "final-results/<uuid:student_pk>/",
        views.FinalResultDetail.as_view(),
        name="final-result-detail",
    ),
    path(
        "students/upload-csv/",
        views.StudentCSVUploadView.as_view(),
        name="student-upload-csv",
    ),
]
